### ISSUE TITLE
dconfi.h doconfig.cpp文件是什么功能相关的代码

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/dtkcore#140]
想给dconfi.h doconfig.cpp编写文档，想知道关于这个文件相关功能的描述

**Comment by xzl01** [comment]
这个应该是系统配置项相关的代码，类似于gsettings相关的内容 cc @kegechen @zccrs

**Comment by chenchongbiao** [comment]
好的，明白了

**Comment by zccrs** [comment]
> 这个应该是系统配置项相关的代码，类似于gsettings相关的内容 cc @kegechen @zccrs

是这个意思。有个设计文档， @kegechen 可以提交到 dtkcore 项目里，当作项目文档提供。

**Comment by xzl01** [comment]
@chenchongbiao  设计文档上传，请完成文档之后@我或者@zccrs @kegechen 进行review

**Comment by chenchongbiao** [comment]
好的

**Comment by zccrs** [comment]
这个文档也公开在了这里：https://github.com/linuxdeepin/deepin-specifications/blob/master/unstable/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%A7%84%E8%8C%83.md ，欢迎查看

**Comment by chenchongbiao** [comment]
> 这个文档也公开在了这里：https://github.com/linuxdeepin/deepin-specifications/blob/master/unstable/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%A7%84%E8%8C%83.md ，欢迎查看

学习了
