### ISSUE TITLE
which gsettings-qt is required ?

### ISSUE THREAD

**Issue by wenheping** [linuxdeepin/dtkcore#15]
Seems the build of dtkcore require gsettings-qt.
I search it and found several gsettings-qt packages, such as:
https://github.com/lirios/qtgsettings 
which gsettings-qt is required by dtkcore ?

**Comment by BLumia** [comment]
We use [gsettings-qt](https://launchpad.net/gsettings-qt), not qtgsettings :)

If you are using Deepin distro, do a `apt build-dep dtkcore` will install all build depts you'll need. You can also get the source via `apt source gsettings-qt`, all you need is enable the `deb-src` repo from your sourcelist.
