### ISSUE TITLE
为什么我在中科大镜像站里安装到的这个工具的版本比这个仓库里的高了0.0.1?

### ISSUE THREAD

**Issue by MCredbear** [linuxdeepin/dtkcore#16]
我的发行版:debian sid arm64

**Comment by BLumia** [comment]
https://packages.debian.org/sid/libdtkcore2

截至目前最新的是 `2.0.13`，而 sid 的是 `2.0.9.17-1`。从你的标题推断来看的话，你可能看错了。

另外开 issue 之前请尽可能多的提供你认为可能相关的信息，比如，你在科大仓库所查询到的实际版本号等。
