### ISSUE TITLE
Deepin Qt5 config have been archived

### ISSUE THREAD

**Issue by tnga** [linuxdeepin/dtkcore#17]
library like [dde-qt-dbus-factory](https://github.com/linuxdeepin/dde-qt-dbus-factory) still depend of [deepin-qt5config](https://github.com/linuxdeepin/deepin-qt5config) on their last source version.
Please, it will be good to know how such dependency break have or will been managed on related project.
It will be also good to archived other deprecated deepin repos.
Thanks!

**Comment by BLumia** [comment]
Should be resolved in https://github.com/linuxdeepin/dde-qt-dbus-factory/pull/7 . Feel free to let us know if you still have any issue.
