### ISSUE TITLE
DtkCore Log

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/dtkcore#188]
[spdlog](https://github.com/gabime/spdlog) 是更加流行的速度更快的log库，可以考虑使用这个log库

另外建议使用qInstallMessageHandler而不是使用宏重定向，这样可以打印出所有的日志包括qml的日志

spdlog本身自带所有功能，可以替代所有旧的实现。

**Comment by xzl01** [comment]
cc @kegechen @zccrs

**Comment by zccrs** [comment]
支持。可以先把 "使用qInstallMessageHandler而不是使用宏重定向" 做了，有兴趣来个提交吗。

**Comment by kegechen** [comment]
其实 qInstallMessageHandler  和 宏的方式都是有的。 
https://github.com/linuxdeepin/dtkcore/blob/master/src/log/Logger.cpp#L658
