### ISSUE TITLE
Doc: [Example documents][dconfigfile.h]

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/dtkcore#217]
## Target files (目标文件)
dconfigfile.zh_CN.dox

## Planned completion time (计划完成时间)
2022/12/21

## Document Type (文档类型)

[] New documents
[] Standardized documents
[] Internationalization of documents
- [x] Example documents

**Comment by chenchongbiao** [comment]
@18202781743 我想问一下我在写DConfigFiel例子， configfile.save()的时候，非全局缓存的话，会拼接用户目录/.config/dsg/configs-fake-global/appid,好像我没看到能设置成全局缓存的函数，或者我选择别的方法，怎么写比较好呢？

**Comment by 18202781743** [comment]
> @18202781743 我想问一下我在写DConfigFiel例子， configfile.save()的时候，非全局缓存的话，会拼接用户目录/.config/dsg/configs-fake-global/appid,好像我没看到能设置成全局缓存的函数，或者我选择别的方法，怎么写比较好呢？

生成全局缓存，是在配置项设置了global，此项有更新之后被调用。
DConfigFile内部默认持有的是全局缓存，对于非全局缓存，是根据用户创建的，
你可以在DConfig的filebackend里看到它的使用，
你也可以在dde-app-services里的dde-dconfig-daemon里看到这个逻辑的处理，

**Comment by chenchongbiao** [comment]
> > @18202781743 我想问一下我在写DConfigFiel例子， configfile.save()的时候，非全局缓存的话，会拼接用户目录/.config/dsg/configs-fake-global/appid,好像我没看到能设置成全局缓存的函数，或者我选择别的方法，怎么写比较好呢？
> 
> 生成全局缓存，是在配置项设置了global，此项有更新之后被调用。 对于缓存，DConfigFile内部有DConfigCacheImpl类去管理，根据flag来判断是全局还是用户级的。 DConfigFile内部默认持有的是全局缓存，对于非全局缓存，是根据用户创建的， 你可以在DConfig的filebackend里看到它的使用， 你也可以在dde-app-services里的dde-dconfig-daemon里看到这个逻辑的处理，

好的 谢谢 我去看看

**Comment by chenchongbiao** [comment]
调用DConfigFile load的时候确实是读取了/usr/share/dsg/configs/appid下的json，但是setValue的时候要加入userCache，数据就保存到用户目录/.config/dsg/configs-fake-global/，我看DConfigFilePrivate里setValue也是需要userCache，那是不是save的时候只允许保存到用户目录下，而不是那个全局目录
