### ISSUE TITLE
关于dconfigfile中缺失的宏以及创建目录的问题

### ISSUE THREAD

**Issue by chenchongbiao** [linuxdeepin/dtkcore#225]
我在src的CMakeLists.txt添加上了，add_definitions(-DD_DSG_APP_DATA_FALLBACK="/var/dsg/appdata")
DConfigCacheImpl类中的globalCacheDir函数下#ifdef D_DSG_APP_DATA_FALLBACK后那段代码能够被成功执行了
##  问题
1. DConfigCacheImpl中save里已经包含了创建保存全局保存目录的代码，但是如果普通用户运行可执行文件，/var/dsg/appdata目录并不会被普通用户创建，虽然文件夹没创建成功，但是mkpath是依然正确执行的，程序并没有报错，如果使用有sudo权限的用户执行，是能够成功创建目录的。
2. 如果找不到全局目录，回退到用户目录下的configs-fake-global，但是也是由于没有权限的问题，创建目录的代码并没有成功执行。

如果需要sudo权限才能创建的目录，普通用户执行能够创建吗，我好像并没有找到。请问有什么可以参考的吗？

**Comment by chenchongbiao** [comment]
@18202781743

**Comment by zccrs** [comment]
“如果找不到全局目录，回退到用户目录下的configs-fake-global，但是也是由于没有权限的问题，创建目录的代码并没有成功执行。”

回退到用户目录下的 configs-fake-global 会失败吗？这个情况是不应该的

**Comment by zccrs** [comment]
app data 目录，一般来说用环境变量 DSG_APP_DATA 指定就行。但是无论用环境变量还是用 D_DSG_APP_DATA_FALLBACK 在编译器指定，都有一个前提，那就是发行版或者桌面环境要准备好这个目录，且它符合dtk的需要（不以root身份运行也有权限编辑目标）。

**Comment by zccrs** [comment]
app data目录设计的意义是，dtk需要一个专为应用程序提供的目录，无论这个程序以哪个用户身份执行，这个目录都能被它读写。这个目录会被应用程序存放一些与用户无关的内容（也就是多个用户之间共享的内容），但是Linux中肯定没有符合这种要求的目录，所以默认没有提供，回退到 configs-fake-global 只是能保证存储这一类配置项时不至于丢失，但是达不到“多个用户之间共享”这个目的了。

**Comment by chenchongbiao** [comment]
> “如果找不到全局目录，回退到用户目录下的configs-fake-global，但是也是由于没有权限的问题，创建目录的代码并没有成功执行。”
> 
> 回退到用户目录下的 configs-fake-global 会失败吗？这个情况是不应该的

也会也需要root权限运行才能成功，不使用root权限，无法从成功创建 configs-fake-global 目录

**Comment by chenchongbiao** [comment]
> app data目录设计的意义是，dtk需要一个专为应用程序提供的目录，无论这个程序以哪个用户身份执行，这个目录都能被它读写。这个目录会被应用程序存放一些与用户无关的内容（也就是多个用户之间共享的内容），但是Linux中肯定没有符合这种要求的目录，所以默认没有提供，回退到 configs-fake-global 只是能保证存储这一类配置项时不至于丢失，但是达不到“多个用户之间共享”这个目的了。

当然如果是提前准备好该目录，并制定了权限的情况下，不使用root权限也可以正常保存

**Comment by zccrs** [comment]
> > “如果找不到全局目录，回退到用户目录下的configs-fake-global，但是也是由于没有权限的问题，创建目录的代码并没有成功执行。”
> > 回退到用户目录下的 configs-fake-global 会失败吗？这个情况是不应该的
> 
> 也会也需要root权限运行才能成功，不使用root权限，无法从成功创建 configs-fake-global 目录

可以看一下拿到的 applicationCacheDir 是什么

**Comment by chenchongbiao** [comment]
使用root情况下成功创建的是root用户的，/root/.config/dsg/configs-fake-global
运行普通用户的时候是在，普通用户目录下的/.config/dsg/configs-fake-global，创建用户缓存的时候是到各自用户目录的/.config/dsg/configs-fake-global下创建
使用了全局缓存的时候是先到/var/dsg/appdata下创建configs目录，当然需要用root权限，否则也是没法创建

**Comment by zccrs** [comment]
> 

/var/dsg/appdata 创建失败是可以预料到的，不算是一个意外情况。

**Comment by chenchongbiao** [comment]
![图片](https://user-images.githubusercontent.com/52627687/209945180-f27d5a2d-12a6-41d7-95e8-96af2bc82a23.png)
那这个宏没定义呢，如果没加宏这段代码没被运行，globalCacheDir直接获得空字符串，

**Comment by zccrs** [comment]
> ![图片](https://user-images.githubusercontent.com/52627687/209945180-f27d5a2d-12a6-41d7-95e8-96af2bc82a23.png) 那这个宏没定义呢，如果没加宏这段代码没被运行，globalCacheDir直接获得空字符串，

正常，这个宏在deepin不应该被定义。globalCacheDir返回一个空字符串的原因是获取到的 appDataDir 为空（在deepin上应该保证这个不为空），DstandardPaths::DSG::AppData 是靠环境变量指定的，应该为程序指定正确的环境变量。

**Comment by chenchongbiao** [comment]
> > ![图片](https://user-images.githubusercontent.com/52627687/209945180-f27d5a2d-12a6-41d7-95e8-96af2bc82a23.png) 那这个宏没定义呢，如果没加宏这段代码没被运行，globalCacheDir直接获得空字符串，
> 
> 正常，这个宏在deepin中不应该被定义。globalCacheDir返回一个空字符串的原因是获取到的 appDataDir 为空（在deepin上应该保证这个不为空），DstandardPaths::DSG::AppData 是靠环境变量指定的，系统应该为程序指定正确的环境变量。

好的 明白了
