### ISSUE TITLE
Compile failed: a header file not found

### ISSUE THREAD

**Issue by ccmywish** [linuxdeepin/dtkcore#267]
![20230215181407](https://user-images.githubusercontent.com/63459097/218999162-f9703aa6-ef42-42c1-a466-66cdab0a0dd9.png)

Can't find this file in source code.

How to solve it? Did I miss something?

**Comment by Decodetalkers** [comment]
you need qt private..if you are on debian

**Comment by Decodetalkers** [comment]
```
qtbase5-private-dev
```
it is the package of debian.

**Comment by ccmywish** [comment]
Thank you. 

But, generally how do I know what lib name I'm missing?

There's no doc on how to build this lib (and other dtk libs), all I know is to install `apt install cmake git qtbase5-dev debhelper dpkg-dev`.  In addition to this, I know nothing.
