### ISSUE TITLE
header files include mess

### ISSUE THREAD

**Issue by ccmywish** [linuxdeepin/dtkcore#275]
The `#include` way we use is not consistent in code.

For example, in header files, 

1. `#include <dtkcore_global.h>` and `#include "dtkcore_global.h"` are both used.
2. Some use `#include <DObject>` and some use `#include "dobject.h"`

In my opinion, 
1. The first issue above must be solved to keep the code clean.  See #276 
2. The second issue, I recommend using `#include "dobject.h"`, it's more conventional (Because we're implementing a library). But this leads to my question below:

--- 
Question:

[`include/DtkCore`](https://github.com/linuxdeepin/dtkcore/tree/master/include/DtkCore) is for client code to use or ourselves to use?

**Comment by Decodetalkers** [comment]
I must say, you need to read more cpp repo learn more about this language..

**Comment by ccmywish** [comment]
@Decodetalkers Thanks for your advice and patience. I'll learn more before contributing to this.
