### ISSUE TITLE
使用QLoggingCategory时，DLog输出"No appenders assotiated with category"

### ISSUE THREAD

**Issue by ArchieMeng** [linuxdeepin/dtkcore#292]
### 现象
使用DLogManager注册Appender之后，
```C++
    DLogManager::registerConsoleAppender();
    DLogManager::registerFileAppender();
```
使用QLoggingCategory输出日志时，会报"No appenders assotiated with category"．且使用Category输出的日志内容没有被记录到日志文件中．
### 期望行为
日志文件记录中不带"No appenders assotiated with category"，且Category输出内容有写入到某个默认日志文件中．

**Comment by ComixHe** [comment]
如果需要使用QLoginCategory、qCWarning之类的日志输出方式，应该调用registerCategoryAppender,否则该category不会被注册到Logger

**Comment by ArchieMeng** [comment]
> 如果需要使用QLoginCategory、qCWarning之类的日志输出方式，应该调用registerCategoryAppender,否则该category不会被注册到Logger

DLogManager无此方法．

**Comment by ComixHe** [comment]
```cpp
#include <LogManager.h>
#include <Logger.h>
#include <dtkcore_global.h>
#include <FileAppender.h>
#include <QLoggingCategory>

#ifndef QT_DEBUG
inline Q_LOGGING_CATEGORY(test, "dtk.test", QtInfoMsg);
#else
inline Q_LOGGING_CATEGORY(test, "dtk.test");
#endif

DCORE_USE_NAMESPACE

int main() {
  DLogManager::registerConsoleAppender();
  DLogManager::registerFileAppender();
  Logger *gLogger = Logger::globalInstance();
  FileAppender *fileAppener = new FileAppender("/tmp/log");
  if (fileAppener->detailsLevel() > Logger::Trace)
    fileAppener->setDetailsLevel(Logger::Trace);
  gLogger->registerCategoryAppender("dtk.test", fileAppener);
  qCWarning(test, "test log");
  return 0;
}
```
这里有一个例子，

**Comment by zccrs** [comment]
> ```c++
> #include <LogManager.h>
> #include <Logger.h>
> #include <dtkcore_global.h>
> #include <FileAppender.h>
> #include <QLoggingCategory>
> 
> #ifndef QT_DEBUG
> inline Q_LOGGING_CATEGORY(test, "dtk.test", QtInfoMsg);
> #else
> inline Q_LOGGING_CATEGORY(test, "dtk.test");
> #endif
> 
> DCORE_USE_NAMESPACE
> 
> int main() {
>   DLogManager::registerConsoleAppender();
>   DLogManager::registerFileAppender();
>   Logger *gLogger = Logger::globalInstance();
>   FileAppender *fileAppener = new FileAppender("/tmp/log");
>   if (fileAppener->detailsLevel() > Logger::Trace)
>     fileAppener->setDetailsLevel(Logger::Trace);
>   gLogger->registerCategoryAppender("dtk.test", fileAppener);
>   qCWarning(test, "test log");
>   return 0;
> }
> ```
> 
> 这里有一个例子，可以参考一下

不太应该让每个程序自己注册（如果这个程序自己不需要对某个 category 做特殊处理的话），举个例子，比如 dxcb 插件中有自己的 category，这就会导致一旦触发 dxcb 的日志（默认至少会输出warning级别）。就会在某个程序的日志文件里看到一行不知所以的警告，这时候是要这个程序自己注册一下对 dxcb 插件里的日志的处理吗？如果有更多的插件要怎么办？

能不能这样：如果没有注册专门的 registerCategoryAppender，全都到默认的 globalAppender 中处理。

**Comment by zccrs** [comment]
> ```c++
> #include <LogManager.h>
> #include <Logger.h>
> #include <dtkcore_global.h>
> #include <FileAppender.h>
> #include <QLoggingCategory>
> 
> #ifndef QT_DEBUG
> inline Q_LOGGING_CATEGORY(test, "dtk.test", QtInfoMsg);
> #else
> inline Q_LOGGING_CATEGORY(test, "dtk.test");
> #endif
> 
> DCORE_USE_NAMESPACE
> 
> int main() {
>   DLogManager::registerConsoleAppender();
>   DLogManager::registerFileAppender();
>   Logger *gLogger = Logger::globalInstance();
>   FileAppender *fileAppener = new FileAppender("/tmp/log");
>   if (fileAppener->detailsLevel() > Logger::Trace)
>     fileAppener->setDetailsLevel(Logger::Trace);
>   gLogger->registerCategoryAppender("dtk.test", fileAppener);
>   qCWarning(test, "test log");
>   return 0;
> }
> ```
> 
> 这里有一个例子，可以参考一下

不太应该让每个程序自己注册（如果这个程序自己不需要对某个 category 做特殊处理的话），举个例子，比如 dxcb 插件中有自己的 category，这就会导致一旦触发 dxcb 的日志（默认至少会输出warning级别）。就会在某个程序的日志文件里看到一行不知所以的警告，这时候是要这个程序自己注册一下对 dxcb 插件里的日志的处理吗？如果有更多的插件要怎么办？

能不能这样：如果没有注册专门的 registerCategoryAppender，全都到默认的 globalAppender 中处理。

**Comment by ComixHe** [comment]
```cpp
    DLogManager::registerConsoleAppender();
    DLogManager::registerFileAppender();
    qCWarning(dtkDefaultCategory()) << "test log";
```
这样可以吗？

**Comment by ComixHe** [comment]
是的，如果不想自己注册category的话统一使用默认的category

**Comment by zccrs** [comment]
> 是的，如果不想自己注册category的话统一使用默认的category, 默认写到`/tmp/rollLog`里

这样没有意义，如果不想注册 category，那跟直接使用 qDebug 这类不带 category 的没有区别。今后我们自己开发的项目的log都会要求按不同的分类使用不同的 category。如果程序使用的 category 都是同样的，那就失去了用 category 的意义。

**Comment by ComixHe** [comment]
但qCWarning必须要提供一个category,并且原来的实现也是提供一个默认的category：
```cpp
#if QT_VERSION >= 0x050000
static void qtLoggerMessageHandler(QtMsgType type, const QMessageLogContext& context, const QString &msg)
{
    Logger::LogLevel level = Logger::Warning;
    switch (type)
    {
    case QtDebugMsg:
        level = Logger::Debug;
        break;
#if QT_VERSION >= 0x050500
    case QtInfoMsg:
        level = Logger::Info;
        break;
#endif
    case QtWarningMsg:
        level = Logger::Warning;
        break;
    case QtCriticalMsg:
        level = Logger::Error;
        break;
    case QtFatalMsg:
        level = Logger::Fatal;
        break;
    }

    bool isDefaultCategory = QString::fromLatin1(context.category) == "default";
    Logger::globalInstance()->write(level, context.file, context.line, context.function,
                                    isDefaultCategory ? nullptr : context.category, msg);
}

#else
```

**Comment by ComixHe** [comment]
已有pr需要验证：https://github.com/linuxdeepin/dtkcore/pull/294

**Comment by zccrs** [comment]
> 已有pr需要验证：#294

在pr的comment和commit信息（注意commit信息里不要写 Close）中关联一下这个issue。

**Comment by ComixHe** [comment]
信息已更新
