### ISSUE TITLE
qmake version in readme

### ISSUE THREAD

**Issue by gaoyaoxin** [linuxdeepin/dtkcore#3]
```
qmake --version
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu
```
I found that the qmake version on my computer which successfully installed this package is 3.0, so should the qmake version line (line 11) in readme be modified into possibly Qt version?

**Comment by aiamuzz** [comment]
hmmmm ... @gaoyaoxin ... i am having trouble installing this package ...

my environment ...
```
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

```
as you've quoted above that you were able to install it succesfully under the environment you've mentioned.

i set out to setup a qmake environment similar to yours.

I have the QtCreator and QtCreator(community) both installed on my system ...

while probing i discovered that qt5-qmake package wasn't to be found so i installed the same ...

`sudo apt-get install qt5-qmake`

though qt4 and qt5 seem to be installed on my system ... i somehow couldn't run this command to configure the version of my choice ...

```
$  sudo update-alternatives --config qmake
update-alternatives: error: no alternatives for qmake
```
so i starting digging deeper ... and did the following ... probably its a manual way to change the version ... or may be not ...

delete the existing sym link ...

`sudo rm /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf`

then i created new symlink to the version of my choice ... by running the following ...

`sudo ln -s /usr/share/qtchooser/qt5-x86_64-linux-gnu.conf /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf`

now `qmake --version` gives an environment that's pretty close to yours.

```
$ qmake --version
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu
```

after this i try to build and install this package ... i get the following error ... 

```
$ qmake ..
$ make
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /media/muz/srcRepo/linux/deepin/tools/dtkcore-master/src/src.pro -o Makefile ) && make -f Makefile 
Project ERROR: gsettings-qt development package not found
Makefile:44: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 3

```

hmmmmm ... back to square one ... not able to install `dtkcore`

**Comment by aiamuzz** [comment]
please note that the default qt environment ... gives the following error while installing ...

```
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

```
https://github.com/linuxdeepin/dtkcore/issues/4

**Comment by gaoyaoxin** [comment]
@aiamuzz 
Possibly there is non-compatibility issue within qt4 and qt5 versions or with default setting concerning qt version.
The distribution I use is deepin 15.5.
Please note that dtkcore is probably originally built for and tested on deepin distributions.

**Comment by aiamuzz** [comment]
@gaoyaoxin ...

Even i am using Deepin 15.5 ... the lastest one ... i am surprised how come your default of qmake version is different to mine ? 

Yours seems to be Version 3.0 and mine turns out to be Version 2.01a !!!

wondering how would get the dtkcore up and running on my system ... hmmmm ...

**Comment by gaoyaoxin** [comment]
@aiamuzz 
I updated the system from deepin 15.4 to 15.5 unstable and then 15.5.
Possibly you may try 
```sudo apt-get update```
or something like that.
It's a really confusing issue.

**Comment by aiamuzz** [comment]
@gaoyaoxin  ...

even I updated the system from deepin 15.4 to 15.5 unstable and then 15.5.

**Comment by aiamuzz** [comment]
Seems the requirement is ...

**Build dependencies
qmake >= 5.3**

and my system is ...
```
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
```

in spite of coming through deepin 15.4 to 15.5 Beta and then 15.5 release ...

would like a little help getting the necessary versions and successfully setting up 'dtk' on my system for academic purposes ...

**Comment by gaoyaoxin** [comment]
@aiamuzz 
Pls try:
```
sudo apt-get update qmake
```
This may help!

**Comment by aiamuzz** [comment]
nope ... `the update command takes no arguments` ... !!!

**Comment by gaoyaoxin** [comment]
```
sudo apt-get update qt5-qmake
```
How about this? Currently I am not using deepin ...

**Comment by aiamuzz** [comment]
nope ... `the update command takes no arguments` ...

**Comment by gaoyaoxin** [comment]
https://github.com/linuxdeepin/dtkcore/blob/master/debian/control
Above is the dependencies.
Possibly try all this by:
```
sudo apt-get install debhelper pkg-config qttools5-dev-tools qtbase5-private-dev libgsettings-qt-dev
```
would help.

**Comment by aiamuzz** [comment]
ok ... i installed ...

`sudo apt-get install debhelper pkg-config qttools5-dev-tools qtbase5-private-dev libgsettings-qt-dev`

and then tried building dtkcore by running the following ...

```
mkdir build
cd build
qmake ..
make
sudo make install
```
how do i check if i've installed it correctly and completely ... can i check the version of dtkcore installed ?

**Comment by gaoyaoxin** [comment]
If it is possibly to complete all the commands above without ERRORs, then dtkcore is supposed to be installed correctly.
Possibly run ```dtkcore``` for version info? I am not sure.

**Comment by aiamuzz** [comment]
i think there were no errors ...

After running those ... i tried building dtkwidget package ... but its not building ...

```
$ make
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /media/muz/srcRepo/linux/deepin/tools/dtkwidget-master/src/src.pro -o Makefile ) && make -f Makefile 
Project ERROR: librsvg-2.0 development package not found
Makefile:44: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 3
```
is it any indication of the dtkcore being installed properly or a lack thereof ?

**Comment by gaoyaoxin** [comment]
Wiki for this repo is not found however helps could be got as suggested at [https://github.com/linuxdeepin/dtkcore#getting-help](url)
Please note that there is an area for English in the forum so it may help [https://bbs.deepin.org/forum.php?mod=forumdisplay&fid=70](url)

**Comment by gaoyaoxin** [comment]
dtkwidget depends on others to be installed
See its depends at [https://github.com/linuxdeepin/dtkwidget/blob/master/debian/control](url) in line 5 to 11

**Comment by aiamuzz** [comment]
ok ... after a fellow githubian pointed me to the required dependencies in the file 'control' (debian folder)

`sudo apt-get install pkg-config libudev-dev qtmultimedia5-dev libqt5x11extras5-dev libxext-dev qttools5-dev-tools x11proto-xext-dev libxcb-util0-dev libstartup-notification0-dev libmtdev-dev qtbase5-private-dev libegl1-mesa-dev libudev-dev libfontconfig1-dev libfreetype6-dev libglib2.0-dev libxrender-dev libdtkcore-dev libgsettings-qt-dev librsvg2-dev libdframeworkdbus-dev  libqt5svg5-dev
`
i was able to get past the above error ... 

```
In file included from ../../src/util/dregionmonitor.cpp:2:0:
../../src/util/private/dregionmonitor_p.h:12:42: fatal error: com_deepin_api_xeventmonitor.h: No such file or directory
 #include <com_deepin_api_xeventmonitor.h>
                                          ^
compilation terminated.
Makefile:1948: recipe for target 'dregionmonitor.o' failed
make[1]: *** [dregionmonitor.o] Error 1
make[1]: Leaving directory '/media/muz/srcRepo/linux/deepin/tools/dtkwidget-master/build/src'
Makefile:44: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2

```

but i am stuck at this error now ...

**Comment by dposea** [comment]
file can be found in https://github.com/linuxdeepin/dde-qt-dbus-factory.git
