### ISSUE TITLE
tools/deepin-os-release/main.cpp: no member named 'isDDE'

### ISSUE THREAD

**Issue by dkarama** [linuxdeepin/dtkcore#38]
I'm trying to build dtkcore-5.4.10 on OpenBSD-current with gsettings-qt-0.2 and deepin-desktop-base-2019.06.14.

This is the build error: [build.log](https://github.com/linuxdeepin/dtkcore/files/6213408/build.log)

**Comment by xmuli** [comment]
Maybe it's the version? The interface is there, see 

https://github.com/linuxdeepin/dtkcore/blob/170f535eadc44b03981c50b18ba6bdfae6fb5b15/src/dsysinfo.cpp#L521

**Comment by dkarama** [comment]
Yes I understand, according to the Makefile in build-amd64/tools/deepin-os-release main.o is compiled with header dsysinfo.h which mentions that interface. What should I try?

**Comment by dkarama** [comment]
Running the following command manually in the source dir still results in failure.
`c++ -I./src -I/usr/local/include/X11/qt5 -I/usr/local/include/X11/qt5/QtCore/ -o main.o tools/deepin-os-release/main.cpp`
So not the fault of BSD make. I tried with Gmake got the same result.

**Comment by kegechen** [comment]
> Yes I understand, according to the Makefile in build-amd64/tools/deepin-os-release main.o is compiled with header dsysinfo.h which mentions that interface. What should I try?

> [https://github.com/linuxdeepin/dtkcore/blob/170f535eadc44b03981c50b18ba6bdfae6fb5b15/src/dsysinfo.cpp#L509](url)

`#ifdef Q_OS_LINUX
...
 bool DSysInfo::isDDE() 
....
#endif`

**Comment by dkarama** [comment]
This will take a long time then, thank you!
Should I close this issue?
