### ISSUE TITLE
dtk的DSingleton单例模板没有声明为虚函数

### ISSUE THREAD

**Issue by realwujing** [linuxdeepin/dtkcore#43]
没有声明为虚函数容易造成内存泄露

析构函数写成virtual的好处：https://blog.csdn.net/heibao111728/article/details/80814313

C++ 单例模式的模板实现：https://zhuanlan.zhihu.com/p/232319083

**Comment by juteman** [comment]
This issue has been fixed

[4804211](https://github.com/linuxdeepin/dtkcore/commit/4804211a53d43603f028d7aed1a0178fa44e48f2)

Thanks for your feedback!
