### ISSUE TITLE
在 uos 1040 环境下，利用qt5.12.3 编译 dtkcore 报如下错误

### ISSUE THREAD

**Issue by czzCreator** [linuxdeepin/dtkcore#46]
cd src/ && /home/zhizhong/qt5.12.3_release_installed/bin/qmake -o Makefile /home/zhizhong/dtkcore/src/src.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

Project ERROR: check dtk version failed

make: *** [/home/zhizhong/build-dtkcore-qt5_12_3_release-Debug/Makefile:43：sub-src-qmake_all] 错误 3

**Comment by czzCreator** [comment]
already   install：

 1191  sudo apt install libdtkcommon-dev 
 1192  sudo apt install libdtkcore-dev 
 1193  sudo apt install libdtkcommon-dev 
 1194  sudo apt install libdtkcore-dev 
 1195  sudo apt install libdtkgui-dev 
 1196  sudo apt install libdtkwidget-dev

**Comment by BLumia** [comment]
抱歉现在才予以答复，我们之前很少关注 developer-center 之外汇报的 issue。

这个检查是 dtkcommon 做的，可以检查一下您所获取的 `dtkcommon.pro` 的行为。默认是从 git tag 获取版本的，并且目前最新版本中默认也会设置一个版本号作为 fallback，所以也可以获取最新代码再尝试一下。

顺便，我们使用 developer-center 处理 issue，如果您仍有问题需要帮助，请移步 https://github.com/linuxdeepin/developer-center/ 和我们联系，感谢！
