### ISSUE TITLE
dfilewatcher.cpp:113:46: 错误

### ISSUE THREAD

**Issue by wldgntlmn** [linuxdeepin/dtkcore#6]
/home/dtkcore-2.0.7/src/filesystem/dfilewatcher.cpp:113:46: 错误：对‘Dtk::Core::DFileWatcher::connect(QGlobalStatic<Dtk::Core::DFileSystemWatcher, (* Dtk::Core::{anonymous}::Q_QGS_watcher_file_private::innerFunction), (* & Dtk::Core::{anonymous}::Q_QGS_watcher_file_private::guard)>&, void (Dtk::Core::DFileSystemWatcher::*)(const QString&, const QString&, Dtk::Core::DFileSystemWatcher::QPrivateSignal), Dtk::Core::DFileWatcher* const&, void (Dtk::Core::DFileWatcher::*)(const QString&, const QString&))’的调用没有匹配的函数
                q, &DFileWatcher::onFileClosed);

make[1]: *** [dfilewatcher.o] 错误 1
make[1]: 离开目录“/home/dtkcore-2.0.7/build/src”
make: *** [sub-src-make_first-ordered] 错误 2

**Comment by Iceyer** [comment]
Please update source to new version an try again.
